# Clustering

```{r}
#| warning: false

library(Seurat)
library(ggplot2)
library(harmony)
source("Palettes.R")
```

```{r}
#ZY_rawcounts <- read.csv('../../data/csv/ZY2019/GSE124952_expression_matrix.csv', header = T, row.names = 1)
#ZY_metadata <- read.csv('../../data/csv/ZY2019/GSE124952_meta_data.csv', header = T, row.names = 1)
#seu_ZY <- CreateSeuratObject(counts = ZY_rawcounts, meta.data = ZY_metadata)
#saveRDS(seu_ZY, '../../data/rds/seu_ZY.rds')
```

```{r}
#| eval: false

all.list <- readRDS('../../data/rds/all.list.rds')
names(all.list) <- c('Adult1', 'Adult2', 'Adult3', 'P0', 'P4', 'P10')
seu_ZY <- readRDS('../../data/rds/seu_ZY.rds')
seu_P21Sample1 <- subset(seu_ZY, cells = colnames(seu_ZY)[which(
  seu_ZY$Sample == "P21Sample1")])
seu_P21Sample2 <- subset(seu_ZY, cells = colnames(seu_ZY)[which(
  seu_ZY$Sample == "P21Sample2")])
seu_P21Sample3 <- subset(seu_ZY, cells = colnames(seu_ZY)[which(
  seu_ZY$Sample == "P21Sample3")])
all.list[["P21Sample1"]] <- seu_P21Sample1
all.list[["P21Sample2"]] <- seu_P21Sample2
all.list[["P21Sample3"]] <- seu_P21Sample3
```


## Harmony

```{r}
seu.combined <- readRDS('../../data/rds/seu.combined.rds')
seu.inte <- readRDS('../../data/rds/all.inte.rds')
seu.combined$seurat_clusters <- seu.inte$seurat_clusters
```


```{r}
seu.combined <- merge(
  x = all.list[[1]], 
  y = list(all.list[[2]],all.list[[3]],all.list[[4]],all.list[[5]],all.list[[6]],all.list[[7]],all.list[[8]],all.list[[9]]), project = "allsamples")
seu.combined <- NormalizeData(seu.combined)
seu.combined <- ScaleData(seu.combined)
seu.combined <- FindVariableFeatures(seu.combined, selection.method = "vst", nfeatures = 2000)
seu.combined <- RunPCA(seu.combined, features = VariableFeatures(object = seu.combined))
```

```{r}
seu.combined <- RunHarmony(seu.combined, "seurat_clusters")
seu.combined <- RunUMAP(seu.combined, reduction = "harmony", dims = 1:30)
```

```{r}
ElbowPlot(seu.combined, ndims = 50, reduction = "harmony")
```


```{r fig.width=10, fig.height=10}
DimPlot(seu.combined, split.by = 'orig.ident', reduction = 'umap', group.by = "seurat_clusters", label = T, ncol = 3, cols = ggsci::pal_igv()(50)) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), 
        axis.text = element_blank(), plot.title = element_text(size = 30)) +
  labs(x='', y='') +
  NoLegend()+
  coord_fixed()
```


## 单独聚类

### MainType

```{r}
all.list <- lapply(X = all.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- ScaleData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
    x <- RunPCA(x, features = VariableFeatures(object = x))
    x <- FindNeighbors(x, dims = 1:10)
    x <- FindClusters(x, resolution = 0.5)
    x <- RunUMAP(x, dims = 1:10, label = T)
})
```

```{r}
all.inte <- readRDS('../../data/rds/all.inte.rds')
DefaultAssay(all.inte) <- "integrated"
all.inte <- ScaleData(all.inte, verbose = FALSE)
all.inte <- RunPCA(all.inte, npcs = 50, verbose = FALSE)
all.inte <- FindNeighbors(all.inte, reduction = "pca", dims = 1:20)
all.inte <- FindClusters(all.inte, resolution = 0.5)
all.inte <- RunUMAP(all.inte, reduction = "pca", dims = 1:20)
```


```{r}
seu <- all.list[[3]]
```

```{r fig.width=5, fig.height=4}
DimPlot(seu, reduction = 'umap', group.by = "RNA_snn_res.0.5", label = T)
```

```{r fig.width=10, fig.height=4}
DotPlot(subset(all.inte, cells=colnames(all.inte)[which(all.inte$Sample=="P21Sample3")]), features = c("Slc17a7","Gad2","Gja1","Flt1","C1qc","Ptgds","Pdgfra","Vtn","Mki67",
                          "Lamp5","Pvalb","Sncg","Sst","Vip",
                          "Pou3f1","Npr3","Syt6","Tshz2"),
        assay = "RNA",
        group.by = "integrated_snn_res.0.5") +
  coord_flip()
```


```{r}
# Adult1
## IT:1,3,4,5,8、PT:6、CT:0,19、NP:15、Pvalb:12、Sst:14、Vip:17、Lamp5:18、Astro:2、Endo:13、VLMC:16、Microglia:7,21、Oligo:11、OPC:10、Unknown:9,20,24,25,26

# Adult2
## IT:1,3,4,5,8、PT:6、CT:0,19、NP:15、Pvalb:12、Sst:14、Vip:17、Lamp5:18、Astro:2、Endo:13、VLMC:16、Microglia:7、Oligo:11、OPC:10、Unknown:9,20,21,23,24,25,26

# Adult3
## IT:1,3,4,5,8、PT:6、CT:0,19、NP:15、Pvalb:12、Sst:14、Vip:17、Lamp5:18、Astro:2、Endo:13、VLMC:16、Microglia:7、Oligo:11、OPC:10、Unknown:9,20,21,23,24,25,26

# P0
## IT:1,3,4,5,8、PT:6、CT:0,19、NP:15、Pvalb:12、Sst:14、Vip:17、Lamp5:18、Astro:2、Endo:13、VLMC:16、Microglia:7、Oligo:11、OPC:10、NSC:20、Unknown:9,22,23,24,25

# P4
## IT:1,3,4,5,8、PT:6、CT:0,19、NP:15、Pvalb:12、Sst:14、Vip:17、Lamp5:18、Astro:2、Endo:13、VLMC:16、Microglia:7、Oligo:11、OPC:10、NSC:20、Unknown:9,21,22,23,24,26

# P10
## IT:1,3,4,5,8、PT:6、CT:0,19、NP:15、Pvalb:12、Sst:14、Vip:17、Lamp5:18、Astro:2、Endo:13、VLMC:16、Microglia:7、Oligo:11、OPC:10、NSC:20、Unknown:9,21,22,23,24,25,26

# P21Sample1
## IT:1,3,4,5,8、PT:6、CT:0,19、NP:15、Pvalb:12、Sst:14、Vip:17、Lamp5:18、Astro:2、Endo:13、VLMC:16、Microglia:7、Oligo:11、OPC:10、Unknown:9,21,24,25,26

# P21Sample2
## IT:1,3,4,5,8、PT:6、CT:0,19、NP:15、Pvalb:12、Sst:14、Vip:17、Lamp5:18、Astro:2、Endo:13、VLMC:16、Microglia:7、Oligo:11、OPC:10、Unknown:9,20,21,23,24,25,26

# P21Sample3
## IT:1,3,4,5,8、PT:6、CT:0,19、NP:15、Pvalb:12、Sst:14、Vip:17、Lamp5:18、Astro:2、Endo:13、VLMC:16、Microglia:7、Oligo:11、OPC:10、Unknown:9,20,21,23,24,26
```

```{r fig.width=5, fig.height=4}
scCustomize::Cluster_Highlight_Plot(
  seurat_object = subset(all.inte, cells = colnames(all.inte)[which(all.inte$Sample=="P21Sample3")]), cluster_name = c("21"), highlight_color = c("navy","forestgreen"))
```


```{r}
sample_all <- c('Adult1', 'Adult2', 'Adult3', 'P0', 'P4', 'P10',
                "P21Sample1", "P21Sample2", "P21Sample3")
for (i in 1:length(all.list)){
  all.list[[i]]@meta.data$Sample <- sample_all[[i]]
}
```

```{r}
features <- SelectIntegrationFeatures(object.list = all.list)
all.anchors <- FindIntegrationAnchors(object.list = all.list, anchor.features = features)
all.inte <- IntegrateData(anchorset = all.anchors)
```

```{r}
DefaultAssay(all.inte) <- "integrated"
all.inte <- ScaleData(all.inte, verbose = FALSE)
all.inte <- RunPCA(all.inte, npcs = 50, verbose = FALSE)
```

```{r}
all.inte <- RunUMAP(all.inte, reduction = "pca", dims = 1:20)
```

```{r}
#all.inte$MainType <- as.character(all.inte$integrated_snn_res.0.5)
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(1,3,4,5,8))] <- "IT"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(6))] <- "PT"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(0,19))] <- "CT"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(15))] <- "NP"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(12))] <- "Pvalb"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(14))] <- "Sst"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(17))] <- "Vip"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(18))] <- "Lamp5"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(2))] <- "Astro"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(13))] <- "Endo"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(16))] <- "VLMC"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(7))] <- "Microglia"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(11))] <- "Oligo"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(10))] <- "OPC"
all.inte$MainType[which(all.inte$Sample=="P21Sample3" & all.inte$integrated_snn_res.0.5 %in% c(9,20,21,23,24,26))] <- "Unknown"
## Excitatory:0,1,3,5,10,12、Inhibitory:8,11、Astro:2、Endo:9、Microglia:6、Oligo:4、OPC:7、Unknown:13,14,15
```

```{r fig.width=10, fig.height=10}
all.inte$Sample <- factor(all.inte$Sample, levels = unique(all.inte$Sample))
DimPlot(subset(all.inte, cells = colnames(all.inte)[which(all.inte$MainType != "Unknown")]), split.by = 'Sample', reduction = 'umap', group.by = "MainType", label = T, ncol = 3, cols = ggsci::pal_igv()(50)) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), 
        axis.text = element_blank(), plot.title = element_text(size = 30)) +
  labs(x='', y='') +
  NoLegend() +
  coord_fixed()
```



```{r}
all.inte <- readRDS("../../data/rds/all.inte.rds")
```

```{r}
# Adult1
## IT:0,1,5、PT:12、CT:3、NP:10、Inhibitory:8,11、Astro:2、Endo:9、VLMC:13,15、Microglia:6、Oligo:4,14、OPC:7、Unknown:
# Adult2
## IT:1,4,7,9、PT:6、CT:2、NP:10、Inhibitory:11,13,14、Astro:0、Endo:8、VLMC:16、Microglia:3,17、Oligo:5,18、OPC:12、Unknown:15
# Adult3
## IT:2,4,14,15、PT:、CT:5、NP:、Inhibitory:8、Astro:3、Endo:6、VLMC:11,12、Microglia:1、Oligo:7、OPC:9、Unknown:0,10,13,16,17,18,19,20,21,22,23
# P0
## IT:0,1,3,7、PT:5、CT:2,6、NP:、Inhibitory:4,9、Astro:8、Endo:12、VLMC:13、Microglia:15、Oligo:、OPC:、NSC:11、Unknown:10,14
# P4
## IT:0,2,3,4、PT:7、CT:1、NP:8、Inhibitory:5,9,10、Astro:6、Endo:13、VLMC:、Microglia:16、Oligo:、OPC:11,14、NSC:12、Unknown:15
# P10
## IT:1,3,6,7、PT:、CT:2,16、NP:11、Inhibitory:4,9、Astro:0、Endo:10、VLMC:15、Microglia:8、Oligo:、OPC:5、NSC:12、Unknown:13,14

# P21Sample2
## IT:1,3,4,5、PT:、CT:2、NP:10、Inhibitory:7,9、Astro:12、Endo:6、VLMC:0、Microglia:13、Oligo:11、OPC:8、NSC:、Unknown:
# P21Sample3
## IT:1,3,4,7、PT:、CT:2、NP:8、Inhibitory:5,10、Astro:12、Endo:6、VLMC:0、Microglia:13、Oligo:11、OPC:9、NSC:、Unknown:
# P21Sample1
## IT:0,2,5,8、PT:、CT:1、NP:12、Inhibitory:7、Astro:10、Endo:6、VLMC:3、Microglia:11、Oligo:4、OPC:9、NSC:、Unknown:
```

```{r}
all.list.order[["P21Sample3"]]$L1_type <- as.character(all.list.order[["P21Sample3"]]$seurat_clusters)
all.list.order[["P21Sample3"]]$L1_type[which(all.list.order[["P21Sample3"]]$L1_type %in% c(1,3,4,7))] <- "IT"
#all.list.order[["P21Sample1"]]$L1_type[which(all.list.order[["P21Sample1"]]$L1_type %in% c())] <- "PT"
all.list.order[["P21Sample3"]]$L1_type[which(all.list.order[["P21Sample3"]]$L1_type %in% c(2))] <- "CT"
all.list.order[["P21Sample3"]]$L1_type[which(all.list.order[["P21Sample3"]]$L1_type %in% c(8))] <- "NP"
all.list.order[["P21Sample3"]]$L1_type[which(all.list.order[["P21Sample3"]]$L1_type %in% c(5,10))] <- "Inhibitory"
all.list.order[["P21Sample3"]]$L1_type[which(all.list.order[["P21Sample3"]]$L1_type %in% c(12))] <- "Astro"
all.list.order[["P21Sample3"]]$L1_type[which(all.list.order[["P21Sample3"]]$L1_type %in% c(6))] <- "Endo"
all.list.order[["P21Sample3"]]$L1_type[which(all.list.order[["P21Sample3"]]$L1_type %in% c(0))] <- "VLMC"
all.list.order[["P21Sample3"]]$L1_type[which(all.list.order[["P21Sample3"]]$L1_type %in% c(13))] <- "Microglia"
all.list.order[["P21Sample3"]]$L1_type[which(all.list.order[["P21Sample3"]]$L1_type %in% c(11))] <- "Oligo"
all.list.order[["P21Sample3"]]$L1_type[which(all.list.order[["P21Sample3"]]$L1_type %in% c(9))] <- "OPC"
#all.list.order[["P21Sample1"]]$L1_type[which(all.list.order[["P21Sample1"]]$L1_type %in% c())] <- "NSC"
#all.list.order[["P21Sample1"]]$L1_type[which(all.list.order[["P21Sample1"]]$L1_type %in% c())] <- "Unknown"
  
# P21Sample3
## IT:1,3,4,7、PT:、CT:2、NP:8、Inhibitory:5,10、Astro:12、Endo:6、VLMC:0、Microglia:13、Oligo:11、OPC:9、NSC:、Unknown:
```


```{r fig.width=6, fig.height=6}
seu <- all.list.order[["P21Sample3"]]
DimPlot(seu,
  #subset(seu, cells = colnames(seu)[which(seu$MainType != "Unknown")]),
        reduction = 'umap', group.by = "L1_type", label = T, 
        cols = ggsci::pal_igv()(50)) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), 
        axis.text = element_blank(), plot.title = element_text(size = 30)) +
  labs(x='', y='', title = "") +
  NoLegend() +
  coord_fixed()
```



```{r}
all.list.order <- list()
all.list.order[["Adult1"]] <- all.list$Adult1
all.list.order[["Adult2"]] <- all.list$Adult2
all.list.order[["Adult3"]] <- all.list$Adult3
all.list.order[["P0"]] <- all.list$P0
all.list.order[["P4"]] <- all.list$P4
all.list.order[["P10"]] <- all.list$P10
all.list.order[["P21Sample1"]] <- all.list$P21Sample1
all.list.order[["P21Sample2"]] <- all.list$P21Sample2
all.list.order[["P21Sample3"]] <- all.list$P21Sample3
```


```{r fig.width=5, fig.height=4}
scCustomize::Cluster_Highlight_Plot(
  seurat_object = seu, cluster_name = c("13"), highlight_color = c("navy","forestgreen"))
```


```{r fig.width=6, fig.height=6}
seu <- all.list[[9]]
seu$MainType <- all.inte$MainType[match(colnames(seu), colnames(all.inte))]
seu$integrated_snn_res.0.5 <- all.inte$integrated_snn_res.0.5[match(colnames(seu), colnames(all.inte))]
MainType_order <- c("IT","PT","CT","NP","Vip","Lamp5","Sst","Pvalb",
                    "Astro","Endo","VLMC","Microglia","Oligo","OPC","NSC","Unknown")
seu$MainType <- factor(seu$MainType, levels = MainType_order)
DimPlot(seu,
  #subset(seu, cells = colnames(seu)[which(seu$MainType != "Unknown")]),
        reduction = 'umap', group.by = "seurat_clusters", label = T, 
        cols = ggsci::pal_igv()(50)) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), 
        axis.text = element_blank(), plot.title = element_text(size = 30)) +
  labs(x='', y='', title = "") +
  NoLegend() +
  coord_fixed()
```


```{r fig.width=12, fig.height=4}
VlnPlot(seu, features = c("nCount_RNA","nFeature_RNA","percent.mt"),
        group.by = "seurat_clusters")
```




```{r fig.width=15, fig.height=9}
FeaturePlot(
  seu,
  ncol = 1,
  features = c(
  #"Npr3","Syt6","Tshz2","Vip","Lamp5","Sst","Pvalb",
  #"Gja1","Flt1","C1qc","Ptgds","Pdgfra","Vtn","Mki67"
    "Ptgds"
  )) +
  coord_fixed()
```


```{r fig.width=12, fig.height=4}
DotPlot(seu, features = c("Slc17a7","Npr3","Syt6","Tshz2","Gad2","Vip","Lamp5","Sst","Pvalb",
  "Gja1","Flt1","Vtn","C1qc","Ptgds","Pdgfra","Mki67"),
        assay = "RNA",
        group.by = "seurat_clusters") +
  coord_flip()
```

## new cluster

```{r}
all.list <- readRDS("../../data/rds/all.list.rds")
```

```{r fig.width=6, fig.height=6}
seu <- all.list[[8]]
DimPlot(subset(seu, cells = colnames(seu)[which(seu$L1_type != "Unknown")]),
        #seu,
        reduction = 'umap', group.by = "L1_type", label = T, 
        cols = col_MainType) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), 
        axis.text = element_blank(), plot.title = element_text(size = 30)) +
  labs(x='', y='', title = "") +
  NoLegend() +
  coord_fixed()
```


```{r}
FeaturePlot(seu, features = c("Npr3")) + coord_fixed()
```


### Harmony

```{r}
all.list <- readRDS("../../data/rds/all.list.rds")
seu.combined <- readRDS('../../data/rds/seu.combined.pca.rds')
seu.combined$L1_type <- "other"

seu.combined$L1_type[match(colnames(all.list[["Adult1"]]),colnames(seu.combined))] <- all.list[["Adult1"]]$L1_type
seu.combined$L1_type[match(colnames(all.list[["Adult2"]]),colnames(seu.combined))] <- all.list[["Adult2"]]$L1_type
seu.combined$L1_type[match(colnames(all.list[["Adult3"]]),colnames(seu.combined))] <- all.list[["Adult3"]]$L1_type
seu.combined$L1_type[match(colnames(all.list[["P0"]]),colnames(seu.combined))] <- all.list[["P0"]]$L1_type
seu.combined$L1_type[match(colnames(all.list[["P4"]]),colnames(seu.combined))] <- all.list[["P4"]]$L1_type
seu.combined$L1_type[match(colnames(all.list[["P10"]]),colnames(seu.combined))] <- all.list[["P10"]]$L1_type
seu.combined$L1_type[match(colnames(all.list[["P21Sample1"]]),colnames(seu.combined))] <- all.list[["P21Sample1"]]$L1_type
seu.combined$L1_type[match(colnames(all.list[["P21Sample2"]]),colnames(seu.combined))] <- all.list[["P21Sample2"]]$L1_type
seu.combined$L1_type[match(colnames(all.list[["P21Sample3"]]),colnames(seu.combined))] <- all.list[["P21Sample3"]]$L1_type

seu.combined <- seu.combined[,!(seu.combined$orig.ident %in% c("P21Sample1","P21Sample2","P21Sample3"))]
```

```{r fig.width=10, fig.height=10}
df <- as.data.frame(seu.combined@reductions$pca@cell.embeddings[,1:2])
df$L1_type <- seu.combined$L1_type
df$data <- seu.combined$orig.ident

ggplot(df, aes(x=PC_1, y=PC_2, color=data)) +
  geom_point()
```


```{r}
seu.combined <- RunHarmony(seu.combined, "orig.ident")
seu.combined <- RunUMAP(seu.combined, reduction = "harmony", dims = 1:30)
seu.combined <- FindNeighbors(seu.combined, reduction = "harmony", dims = 1:30)
seu.combined <- FindClusters(seu.combined, reduction = "harmony", resolution = 0.5)
```


```{r fig.width=15, fig.height=8}
DimPlot(seu.combined,
  #subset(seu, cells = colnames(seu)[which(seu$MainType != "Unknown")]),
        reduction = 'umap', group.by = "L1_type", label = T, split.by = "orig.ident", ncol = 3, cols = ggsci::pal_igv()(50)) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), 
        axis.text = element_blank(), plot.title = element_text(size = 30)) +
  labs(x='', y='', title = "") +
  NoLegend() +
  coord_fixed()
```


```{r fig.width=10, fig.height=10}
df <- as.data.frame(seu.combined@reductions$harmony@cell.embeddings[,1:2])
df$L1_type <- seu.combined$L1_type
df$data <- seu.combined$orig.ident

ggplot(df, aes(x=harmony_1, y=harmony_2, color=data)) +
  geom_point()
```


## harm

```{r}
seu.combined.harmony <- readRDS("../../data/rds/seu.combined.harmony.rds")
```


```{r}
DimPlot(seu.combined,
        reduction = 'umap', group.by = "L1_type", label = T, split.by = "orig.ident", ncol = 5, cols = ggsci::pal_igv()(50)) +
  theme(axis.line = element_blank(), axis.ticks = element_blank(), 
        axis.text = element_blank(), plot.title = element_text(size = 30)) +
  labs(x='', y='', title = "") +
  NoLegend() +
  coord_fixed()
```





```{r}
meta_name <- c('orig.ident','nCount_RNA','nFeature_RNA','percent.mt','RNA_snn_res.0.5',
               'seurat_clusters','L1_type')
seu.combined@meta.data <- seu.combined@meta.data[,meta_name]
```






## 批次效应

```{r}
all.list <- readRDS('../../data/rds/old/all.list.rds')
seu.harmony <- readRDS('../data/seu.harmony.rds')
seu.harmony.metadata <- readRDS('../data/seu.harmony.metadata.rds')
seu.harmony@meta.data <- seu.harmony.metadata
```


```{r fig.width=6, fig.height=4}
df1 <- data.frame(
  PC_1 = all.list[["P0"]]@reductions$pca@cell.embeddings[,"PC_1"],
  PC_2 = seu.harmony@reductions$pca@cell.embeddings[,"PC_2"],
  Sample = seu.harmony$orig.ident
)
df1$Sample <- factor(df1$Sample, levels = c("P1","P4","P10","Adult"))
df1 <- df1[order(df1$Sample),]

p1 <- 
  ggplot(df1, aes(x=PC_1, y=PC_2, color=Sample)) +
  geom_point(size=0.5) +
  scale_color_manual(values=col_Time) +
  theme_classic() +
  coord_fixed()
```





```{r fig.width=6, fig.height=4}
df1 <- data.frame(
  PC_1 = seu@reductions$pca@cell.embeddings[,"PC_1"],
  PC_2 = seu@reductions$pca@cell.embeddings[,"PC_2"],
  Sample = seu$orig.ident
)
df1$Sample <- factor(df1$Sample, levels = c("P1","P4","P10","Adult"))
df1 <- df1[order(df1$Sample),]

p1 <- 
  ggplot(df1, aes(x=PC_1, y=PC_2, color=Sample)) +
  geom_point(size=0.5) +
  scale_color_manual(values=col_Time) +
  theme_classic() +
  coord_fixed()
```


```{r fig.width=6, fig.height=4}
df1 <- data.frame(
  PC_1 = seu@reductions$harmony@cell.embeddings[,"harmony_1"],
  PC_2 = seu@reductions$harmony@cell.embeddings[,"harmony_2"],
  Sample = seu$orig.ident
)
df1$Sample <- factor(df1$Sample, levels = c("P1","P4","P10","Adult"))
df1 <- df1[order(df1$Sample),]

p2 <- 
  ggplot(df1, aes(x=PC_1, y=PC_2, color=Sample)) +
  geom_point(size=0.5) +
  scale_color_manual(values=col_Time) +
  theme_classic() +
  coord_fixed()
```


```{r fig.width=8, fig.height=4}
p <- cowplot::plot_grid(p1, p2)
p
```

```{r}
ggsave("../../Figure/毕业论文/Harmony.pdf", plot = p,
       height = 4, width = 8, units = "in")
```




```{r}
seu <- seu.harmony
seu <- NormalizeData(seu)
seu <- FindVariableFeatures(seu, nfeatures = 2000)
seu <- ScaleData(seu)
seu <- RunPCA(seu, features = VariableFeatures(object = seu))
seu <- RunUMAP(seu, reduction = "pca", dims = 1:30)

seu <- RunHarmony(seu, "orig.ident")
```



```{r fig.width=4, fig.height=4}
DimPlot(seu, reduction = 'umap', group.by = "orig.ident", label = F, 
        cols = col_Time) +
  theme_classic() +
  coord_fixed()
```



