```{r}
#| warning: false
#| message: false

library(Seurat)
library(tidyverse)
library(scRNAtoolVis)
library(SeuratDisk)
library(stringr)
library(cowplot)
library(SpaGene)
source('bin/Palettes.R')
```


```{r}
#| warning: false
#| message: false

seu.harmony <- readRDS('../data/seu.harmony.rds')
seu.harmony.metadata <- readRDS('../data/seu.harmony.metadata.rds')
seu.harmony@meta.data <- seu.harmony.metadata
```


## 1

```{r}
df <- seu.harmony@meta.data[,c("orig.ident","SubType")]
df <- table(df$orig.ident, df$SubType)
df <- as.data.frame.array(df/rowSums(df))
CV <- apply(df, 2, function(x){(sd(x)/mean(x))})
CV <- as.data.frame(CV)
CV$Type <- rownames(CV)
CV <- CV[CV$Type %in% names(col_SubType)[1:15],]
CV <- CV[order(CV$CV),]
```

```{r fig.width=10, fig.height=5}
p <- ggplot(CV, aes(x=Type, y=CV, fill=Type)) +
  geom_col() +
  scale_fill_manual(values = col_SubType) +
  theme_classic(base_size = 15) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(color = "black")) +
  labs(x="", y="Coefficient of variation")
p
```

```{r}
#| eval: false

ggsave("../../Figure/Revision/Response_Fig1.pdf", plot = p,
       height = 5, width = 10, units = "in")
```


## 2

```{r fig.width=6, fig.height=6}
#| message: false
#| warning: false

DEGs_all <- read.csv("../data/Figure2/DEGs_Time_Neuron.csv")
DEGs_all <- DEGs_all[,-1]
colnames(DEGs_all)[6] <- "cluster"

P4_cluster <- c("P4_IT","P4_PT","P4_NP","P4_CT","P4_Lamp5","P4_Pvalb","P4_Sst","P4_Vip")
P10_cluster <- c("P10_IT","P10_PT","P10_NP","P10_CT","P10_Lamp5","P10_Pvalb","P10_Sst","P10_Vip")
Adult_cluster <- c("Adult_IT","Adult_PT","Adult_NP","Adult_CT","Adult_Lamp5","Adult_Pvalb","Adult_Sst","Adult_Vip")
P4_vs_P0_DEGs <- DEGs_all[DEGs_all$cluster %in% P4_cluster,]
P10_vs_P4_DEGs <- DEGs_all[DEGs_all$cluster %in% P10_cluster,]
Adult_vs_P10_DEGs <- DEGs_all[DEGs_all$cluster %in% Adult_cluster,]

tile.col <- c("IT"="#0a6ddd","PT"="#a1bc6a","NP"="#f7bc3e","CT"="#f7fa10",
              "Lamp5"="#0e0786","Pvalb"="#6902a4","Sst"="#df6361","Vip"="#31b69e")
Adult_vs_P10_DEGs$cluster <- gsub("Adult_","",Adult_vs_P10_DEGs$cluster)
Adult_vs_P10_DEGs_filter <- Adult_vs_P10_DEGs[-grep("Gm", Adult_vs_P10_DEGs$gene),]
Adult_vs_P10_DEGs_filter$cluster <- factor(Adult_vs_P10_DEGs_filter$cluster,
                                       levels = names(tile.col))
Figure_2D_1 <- 
  jjVolcano(diffData = Adult_vs_P10_DEGs_filter, 
          aesCol = c('purple','orange'),
          topGeneN = 0,
          tile.col = tile.col,
          size = 2, segment.size = 0.1,
          fontface = 'italic',
          polar = F,
          seed = 20230727)+
  ylim(-4.5,4.5) +
  labs(title = '',x="",y="") +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none", axis.text.y = element_blank(),
        axis.title.x = element_blank())
Figure_2D_1
```

```{r}
#| eval: false

ggsave("../../Figure/Figure2/Figure_2D_3.png", plot = Figure_2D_1,
       height = 6, width = 6, units = "in")
```


## 3

```{r fig.width=6, fig.height=6}
#| message: false
#| warning: false

tile.col <- c("IT"="#0a6ddd","PT"="#a1bc6a","NP"="#f7bc3e","CT"="#f7fa10",
              "Lamp5"="#0e0786","Pvalb"="#6902a4","Sst"="#df6361","Vip"="#31b69e")
Adult_vs_P10_DEGs$cluster <- gsub("Adult_","",Adult_vs_P10_DEGs$cluster)
Adult_vs_P10_DEGs$cluster <- factor(Adult_vs_P10_DEGs$cluster,
                                levels = names(tile.col))
Adult_vs_P10_DEGs <- Adult_vs_P10_DEGs[,-1]
Figure_4A_1 <- 
  jjVolcano(diffData = Adult_vs_P10_DEGs, 
          aesCol = c('purple','orange'),
          topGeneN = 0,
          tile.col = tile.col,
          size = 2, segment.size = 0.1,
          fontface = 'italic',
          polar = F,
          seed = 20230727)+
  ylim(-4.5,4.5) +
  labs(title = '',x='',y='') +
  theme(plot.title = element_text(hjust = 0.5),
        legend.position = "none",
        axis.title.x = element_blank())
Figure_4A_1
```

```{r}
#| eval: false

ggsave("../../Figure/Figure4/Figure_4A_1.pdf", plot = Figure_4A_1,
       height = 6, width = 6, units = "in")
```



```{r fig.width=10, fig.height=5}
seu <- seu.harmony
seu$orig.ident <- factor(seu$orig.ident, levels = c("P1","P4","P10","Adult"))
 VlnPlot(seu[,seu$orig.ident=="Adult"], features = "Mog", group.by = "SubType",
         cols = col_SubType) + NoLegend()
```

```{r fig.width=12, fig.height=3}
seu <- seu.harmony
seu$orig.ident <- factor(seu$orig.ident, levels = c("P1","P4","P10","Adult"))
FeaturePlot(seu, features = "Mog", split.by = "orig.ident", ncol = 2) &
  theme_void() & NoLegend() &
  theme(plot.title = element_text(hjust = 0.5))
```


## 4

```{r}
seu.harmony <- readRDS('../data/seu.harmony.rds')
seu.harmony.metadata <- readRDS('../data/seu.harmony.metadata.rds')
seu.harmony@meta.data <- seu.harmony.metadata
```

```{r}
seu <- seu.harmony
seu$Time_Subtype <- paste(seu$orig.ident, seu$SubType)
seu <- seu[,!seu$Time_Subtype %in% c("P1 L2/3 IT","P1 L4/5 IT","P1 L5 IT","P1 Endo",
                        "P4 L2/3 IT","P4 L4/5 IT","P4 Endo","P10 Endo",
                        "Adult Im L2/3 IT","Adult Im L4/5 IT","Adult Im L5 IT","Adult Im L6 IT",
                        "Adult Endo","Adult NPC"
                        )]
```

```{r}


counts <- seu@assays$RNA$counts
rownames(counts) <- str_to_upper(rownames(counts))
seu_h5ad <- CreateSeuratObject(counts = counts,
                               meta.data = seu@meta.data)
SaveH5Seurat(seu_h5ad, filename = "../../data/Revision/seu.h5Seurat")
Convert("../../data/Revision/seu.h5Seurat", dest = "h5ad")
file.remove("../../data/Revision/seu.h5Seurat")
```

```{r}
cov <- data.frame("cell_id"=colnames(seu_h5ad), "const"=rep(1,ncol(seu_h5ad)),
                  "n_genes"=seu_h5ad$nFeature_RNA)
write_tsv(cov, "../../data/Revision/cov.tsv")
```

### 比较

```{r}
disease_gene_list <- read.csv("../data/Figure6/disease_gene_lib.csv")
seu <- seu.harmony
seu$Time_Subtype <- paste(seu$orig.ident, seu$SubType)
seu <- seu[,!seu$Time_Subtype %in% c("P1 L2/3 IT","P1 L4/5 IT","P1 L5 IT","P1 Endo","P4 L2/3 IT","P4 L4/5 IT","P4 Endo","P10 Endo","Adult Im L2/3 IT","Adult Im L4/5 IT","Adult Im L5 IT","Adult Im L6 IT","Adult Endo","Adult NPC")]

for (i in 1:8){
  disease <- names(col_Disease)[i]
  gene_list <- disease_gene_list[,disease]
  gene_list <- gene_list[gene_list %in% rownames(seu)]
  gene_list <- list('disease'=gene_list)
  seu <- AddModuleScore(
    object=seu, 
    features = gene_list, ctrl = 100, name = disease
    )
}
```

```{r}
scDRS_score <- read.csv("../../data/Revision/result/dict_score.csv")
All_score <- seu@meta.data[,c("ADHD1","BD1","MDD1","SCZ1")]
All_score$ADHD <- scDRS_score$ADHD[match(rownames(All_score), scDRS_score$X)]
All_score$BD <- scDRS_score$BP[match(rownames(All_score), scDRS_score$X)]
All_score$MDD <- scDRS_score$MDD[match(rownames(All_score), scDRS_score$X)]
All_score$SCZ <- scDRS_score$SCZ[match(rownames(All_score), scDRS_score$X)]

All_score$MDD <- (All_score$MDD - min(All_score$MDD)) / 
  (max(All_score$MDD) - min(All_score$MDD))
All_score$MDD1 <- (All_score$MDD1 - min(All_score$MDD1)) / 
  (max(All_score$MDD1) - min(All_score$MDD1))
```

```{r}
ggplot(All_score, aes(x=MDD1, y=MDD)) +
  geom_point() +
  geom_smooth()
```

```{r}
disease_result <- read.csv("../data/Figure6/disease_result.csv")
scDRS_score <- read.csv("../../data/Revision/result/dict_score.csv")
seu.harmony.metadata <- readRDS('../data/seu.harmony.metadata.rds')
scDRS_score$SubType <- seu.harmony.metadata$SubType[match(scDRS_score$X, rownames(seu.harmony.metadata))]
scDRS_score$orig.ident <- seu.harmony.metadata$orig.ident[match(scDRS_score$X, rownames(seu.harmony.metadata))]
scDRS_score$Time_Subtype <- paste(scDRS_score$orig.ident, scDRS_score$SubType)
scDRS_score <- scDRS_score[!scDRS_score$Time_Subtype %in% c("P1 L2/3 IT","P1 L4/5 IT","P1 L5 IT","P1 Endo","P4 L2/3 IT","P4 L4/5 IT","P4 Endo","P10 Endo","Adult Im L2/3 IT","Adult Im L4/5 IT","Adult Im L5 IT","Adult Im L6 IT","Adult Endo","Adult NPC"),]
scDRS_mean <- scDRS_score %>%
  group_by(Time_Subtype) %>%
  summarise(across(13:16, mean, na.rm = TRUE))

ADHD <- disease_result[disease_result$Disease=="ADHD",
                       c("CellType", "Time", "sd_from_mean")]
ADHD$scDRS_mean <- scDRS_mean$ADHD[match(ADHD$CellType, scDRS_mean$Time_Subtype)]
ADHD$sd_from_mean <- (ADHD$sd_from_mean - min(ADHD$sd_from_mean)) / 
  (max(ADHD$sd_from_mean) - min(ADHD$sd_from_mean))
ADHD$scDRS_mean <- (ADHD$scDRS_mean - min(ADHD$scDRS_mean)) / 
  (max(ADHD$scDRS_mean) - min(ADHD$scDRS_mean))

BD <- disease_result[disease_result$Disease=="BD",
                       c("CellType", "Time", "sd_from_mean")]
BD$scDRS_mean <- scDRS_mean$BP[match(BD$CellType, scDRS_mean$Time_Subtype)]
BD$sd_from_mean <- (BD$sd_from_mean - min(BD$sd_from_mean)) / 
  (max(BD$sd_from_mean) - min(BD$sd_from_mean))
BD$scDRS_mean <- (BD$scDRS_mean - min(BD$scDRS_mean)) / 
  (max(BD$scDRS_mean) - min(BD$scDRS_mean))
```





```{r}
order <- paste(rep(c("P1","P4","P10","Adult"), each=21),
               rep(names(col_SubType),4))
order <- order[order %in% scDRS_mean$Time_Subtype]
scDRS_mean$Time_Subtype <- factor(scDRS_mean$Time_Subtype, levels = order)
scDRS_mean$Time <- factor(scDRS_mean$Time, levels = c("P1","P4","P10","Adult"))

Figure_6A <- 
  ggplot(data = scDRS_mean, mapping = aes(x = Time_Subtype, y = ADHD, fill = Time)) +
  geom_bar(stat = 'identity') + 
  #facet_grid(Disease ~ .) + 
  scale_fill_manual(values = col_Time) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7),
        panel.grid = element_blank(), panel.border = element_blank(),
        legend.position = "top")
Figure_6A
```

```{r fig.width=10, fig.height=10}
scDRS_score$UMAP_1 <- seu.harmony.metadata[scDRS_score$X,'UMAP_1']
scDRS_score$UMAP_2 <- seu.harmony.metadata[scDRS_score$X,'UMAP_2']

ggplot(scDRS_score, aes(x=UMAP_1, y=UMAP_2, color=ADHD)) +
  geom_point() +
   scale_color_gradientn(colours = c("lightgray", "white", "red")) +
  theme_void()
```

## 5. 分开分析

```{r}
seu.harmony <- readRDS('../data/seu.harmony.rds')
seu.harmony.metadata <- readRDS('../data/seu.harmony.metadata.rds')
seu.harmony@meta.data <- seu.harmony.metadata
```

```{r}
seu <- seu.harmony
seu$Time_Subtype <- paste(seu$orig.ident, seu$SubType)
seu <- seu[,!seu$Time_Subtype %in% c(
  "P1 L2/3 IT","P1 L4/5 IT","P1 L5 IT","P1 Endo",
  "P4 L2/3 IT","P4 L4/5 IT","P4 Endo",
  "P10 Endo",
  "Adult Im L2/3 IT","Adult Im L4/5 IT","Adult Im L5 IT","Adult Im L6 IT",
  "Adult Endo","Adult NPC")]
seu_P1 <- seu[,seu$orig.ident=="P1"]
seu_P4 <- seu[,seu$orig.ident=="P4"]
seu_P10 <- seu[,seu$orig.ident=="P10"]
seu_Adult <- seu[,seu$orig.ident=="Adult"]
```

```{r}
counts <- seu_Adult@assays$RNA$counts
rownames(counts) <- str_to_upper(rownames(counts))
seu_h5ad <- CreateSeuratObject(counts = counts,
                               meta.data = seu_Adult@meta.data)
SaveH5Seurat(seu_h5ad, filename = "../../data/Revision/seu_Adult.h5Seurat")
Convert("../../data/Revision/seu_Adult.h5Seurat", dest = "h5ad")
file.remove("../../data/Revision/seu_Adult.h5Seurat")
```

```{r}
cov_P1 <- data.frame("cell_id"=colnames(seu_P1), "const"=rep(1,ncol(seu_P1)),
                  "n_genes"=seu_P1$nFeature_RNA)
write_tsv(cov_P1, "../../data/Revision/cov_P1.tsv")

cov_P4 <- data.frame("cell_id"=colnames(seu_P4), "const"=rep(1,ncol(seu_P4)),
                  "n_genes"=seu_P4$nFeature_RNA)
write_tsv(cov_P4, "../../data/Revision/cov_P4.tsv")

cov_P10 <- data.frame("cell_id"=colnames(seu_P10), "const"=rep(1,ncol(seu_P10)),
                  "n_genes"=seu_P10$nFeature_RNA)
write_tsv(cov_P10, "../../data/Revision/cov_P10.tsv")

cov_Adult <- data.frame("cell_id"=colnames(seu_Adult),
                        "const"=rep(1,ncol(seu_Adult)),
                  "n_genes"=seu_Adult$nFeature_RNA)
write_tsv(cov_Adult, "../../data/Revision/cov_Adult.tsv")
```

```{r}
disease_result <- read.csv("../data/Figure6/disease_result.csv")
ADHD <- disease_result[disease_result$Disease=="ADHD",]
BP <- disease_result[disease_result$Disease=="BD",]
MDD <- disease_result[disease_result$Disease=="MDD",]
SCZ <- disease_result[disease_result$Disease=="SCZ",]

P1_score <- read.csv(".../../../../data/Revision/P1/P1_score.csv", row.names = 1)
P4_score <- read.csv(".../../../../data/Revision/P4/P4_score.csv", row.names = 1)
P10_score <- read.csv(".../../../../data/Revision/P10/P10_score.csv", row.names = 1)
Adult_score <- read.csv(".../../../../data/Revision/Adult/Adult_score.csv", row.names = 1)
scDRS_score <- rbind(P1_score,P4_score,P10_score,Adult_score)

scDRS_mean <- scDRS_score %>%
  group_by(Time_Subtype) %>%
  summarise(across(13:16, mean, na.rm = TRUE))

scDRS_mean$ADHD1 <- ADHD$sd_from_mean[match(scDRS_mean$Time_Subtype, ADHD$CellType)]
scDRS_mean$BP1 <- BP$sd_from_mean[match(scDRS_mean$Time_Subtype, BP$CellType)]
scDRS_mean$MDD1 <- MDD$sd_from_mean[match(scDRS_mean$Time_Subtype, MDD$CellType)]
scDRS_mean$SCZ1 <- SCZ$sd_from_mean[match(scDRS_mean$Time_Subtype, SCZ$CellType)]
```

```{r}
ggplot(scDRS_mean, aes(x=MDD, y=MDD1)) +
  geom_point()
```




## GWAS

### MAGMA output 转换

```{r}
library(clusterProfiler)

# ANO
ANO <- read.table("../../data/GWAS/ANO.genes.out", header = T)
s2ens = bitr(ANO$GENE, fromType="ENTREZID", toType="SYMBOL",
             OrgDb="org.Hs.eg.db")
ANO <- subset(ANO, ANO$GENE %in% s2ens$ENTREZID)
ANO$gene_symbol <- s2ens$SYMBOL
ANO <- data.frame("GENE" = ANO$gene_symbol, "ANO"=ANO$ZSTAT)
write.table(ANO, file='../../data/GWAS/ANO.tsv', row.names=F, sep="\t", quote=F)

# ASD
ASD <- read.table("../../data/GWAS/ASD.genes.out", header = T)
s2ens = bitr(ASD$GENE, fromType="ENTREZID", toType="SYMBOL",
             OrgDb="org.Hs.eg.db")
ASD <- subset(ASD, ASD$GENE %in% s2ens$ENTREZID)
ASD$gene_symbol <- s2ens$SYMBOL
ASD <- data.frame("GENE" = ASD$gene_symbol, "ASD"=ASD$ZSTAT)
write.table(ASD, file='../../data/GWAS/ASD.tsv', row.names=F, sep="\t", quote=F)

# OCD
OCD <- read.table("../../data/GWAS/OCD.genes.out", header = T)
s2ens = bitr(OCD$GENE, fromType="ENTREZID", toType="SYMBOL",
             OrgDb="org.Hs.eg.db")
OCD <- subset(OCD, OCD$GENE %in% s2ens$ENTREZID)
OCD$gene_symbol <- s2ens$SYMBOL
OCD <- data.frame("GENE" = OCD$gene_symbol, "OCD"=OCD$ZSTAT)
write.table(OCD, file='../../data/GWAS/OCD.tsv', row.names=F, sep="\t", quote=F)

# TS
TS <- read.table("../../data/GWAS/TS.genes.out", header = T)
s2ens = bitr(TS$GENE, fromType="ENTREZID", toType="SYMBOL",
             OrgDb="org.Hs.eg.db")
TS <- subset(TS, TS$GENE %in% s2ens$ENTREZID)
TS$gene_symbol <- s2ens$SYMBOL
TS <- data.frame("GENE" = TS$gene_symbol, "TS"=TS$ZSTAT)
write.table(TS, file='../../data/GWAS/TS.tsv', row.names=F, sep="\t", quote=F)

```

### 分开时间点结果

```{r}
P1_score <- read.csv("../../data/Revision/P1/P1_score.csv", row.names = 1)
P4_score <- read.csv("../../data/Revision/P4/P4_score.csv", row.names = 1)
P10_score <- read.csv("../../data/Revision/P10/P10_score.csv", row.names = 1)
Adult_score <- read.csv("../../data/Revision/Adult/Adult_score.csv", row.names = 1)
All_score <- rbind(P1_score, P4_score, P10_score, Adult_score)
All_score <- read.csv("../../data/Revision/All/All_score.csv", row.names = 1)
```

```{r fig.width=20, fig.height=5}
plist <- list()
for (i in 1:8){
  disease <- names(col_Disease)[i]
  df <- data.frame(
    UMAP_1 = All_score$UMAP_1,
    UMAP_2 = All_score$UMAP_2,
    value = scale(All_score[,disease])
  )
  df$value[df$value>3.5] <- 3.5
  df$value[df$value<0] <- 0
  df <- df[order(df$value),]
  plist[[i]] <- 
    ggplot(df, mapping=aes(x=UMAP_1, y=UMAP_2, color=value)) +
    geom_point(size=0.5) +
    theme_void() +
    theme(legend.position = "none") +
    coord_fixed() +
    scale_color_gradientn(colours = c("lightgray", "white", col_Disease[i]), 
                          limits = c(0,3.5))
}
plot_grid(plotlist = plist, ncol = 4)
```

```{r}
# P1
ADHD <- read_tsv("../../data/Revision/P1/ADHD.scdrs_group.Time_Subtype")
ADHD$Disease <- "ADHD"
ADHD$Time <- "P1"
ANO <- read_tsv("../../data/Revision/P1/ANO.scdrs_group.Time_Subtype")
ANO$Disease <- "ANO"
ANO$Time <- "P1"
ASD <- read_tsv("../../data/Revision/P1/ASD.scdrs_group.Time_Subtype")
ASD$Disease <- "ASD"
ASD$Time <- "P1"
BP <- read_tsv("../../data/Revision/P1/BP.scdrs_group.Time_Subtype")
BP$Disease <- "BP"
BP$Time <- "P1"
MDD <- read_tsv("../../data/Revision/P1/MDD.scdrs_group.Time_Subtype")
MDD$Disease <- "MDD"
MDD$Time <- "P1"
OCD <- read_tsv("../../data/Revision/P1/OCD.scdrs_group.Time_Subtype")
OCD$Disease <- "OCD"
OCD$Time <- "P1"
SCZ <- read_tsv("../../data/Revision/P1/SCZ.scdrs_group.Time_Subtype")
SCZ$Disease <- "SCZ"
SCZ$Time <- "P1"
TS <- read_tsv("../../data/Revision/P1/TS.scdrs_group.Time_Subtype")
TS$Disease <- "TS"
TS$Time <- "P1"
P1_Disease <- rbind(ADHD,ANO,ASD,BP,MDD,OCD,SCZ,TS)

# P4
ADHD <- read_tsv("../../data/Revision/P4/ADHD.scdrs_group.Time_Subtype")
ADHD$Disease <- "ADHD"
ADHD$Time <- "P4"
ANO <- read_tsv("../../data/Revision/P4/ANO.scdrs_group.Time_Subtype")
ANO$Disease <- "ANO"
ANO$Time <- "P4"
ASD <- read_tsv("../../data/Revision/P4/ASD.scdrs_group.Time_Subtype")
ASD$Disease <- "ASD"
ASD$Time <- "P4"
BP <- read_tsv("../../data/Revision/P4/BP.scdrs_group.Time_Subtype")
BP$Disease <- "BP"
BP$Time <- "P4"
MDD <- read_tsv("../../data/Revision/P4/MDD.scdrs_group.Time_Subtype")
MDD$Disease <- "MDD"
MDD$Time <- "P4"
OCD <- read_tsv("../../data/Revision/P4/OCD.scdrs_group.Time_Subtype")
OCD$Disease <- "OCD"
OCD$Time <- "P4"
SCZ <- read_tsv("../../data/Revision/P4/SCZ.scdrs_group.Time_Subtype")
SCZ$Disease <- "SCZ"
SCZ$Time <- "P4"
TS <- read_tsv("../../data/Revision/P4/TS.scdrs_group.Time_Subtype")
TS$Disease <- "TS"
TS$Time <- "P4"
P4_Disease <- rbind(ADHD,ANO,ASD,BP,MDD,OCD,SCZ,TS)

# P10
ADHD <- read_tsv("../../data/Revision/P10/ADHD.scdrs_group.Time_Subtype")
ADHD$Disease <- "ADHD"
ADHD$Time <- "P10"
ANO <- read_tsv("../../data/Revision/P10/ANO.scdrs_group.Time_Subtype")
ANO$Disease <- "ANO"
ANO$Time <- "P10"
ASD <- read_tsv("../../data/Revision/P10/ASD.scdrs_group.Time_Subtype")
ASD$Disease <- "ASD"
ASD$Time <- "P10"
BP <- read_tsv("../../data/Revision/P10/BP.scdrs_group.Time_Subtype")
BP$Disease <- "BP"
BP$Time <- "P10"
MDD <- read_tsv("../../data/Revision/P10/MDD.scdrs_group.Time_Subtype")
MDD$Disease <- "MDD"
MDD$Time <- "P10"
OCD <- read_tsv("../../data/Revision/P10/OCD.scdrs_group.Time_Subtype")
OCD$Disease <- "OCD"
OCD$Time <- "P10"
SCZ <- read_tsv("../../data/Revision/P10/SCZ.scdrs_group.Time_Subtype")
SCZ$Disease <- "SCZ"
SCZ$Time <- "P10"
TS <- read_tsv("../../data/Revision/P10/TS.scdrs_group.Time_Subtype")
TS$Disease <- "TS"
TS$Time <- "P10"
P10_Disease <- rbind(ADHD,ANO,ASD,BP,MDD,OCD,SCZ,TS)

# Adult
ADHD <- read_tsv("../../data/Revision/Adult/ADHD.scdrs_group.Time_Subtype")
ADHD$Disease <- "ADHD"
ADHD$Time <- "Adult"
ANO <- read_tsv("../../data/Revision/Adult/ANO.scdrs_group.Time_Subtype")
ANO$Disease <- "ANO"
ANO$Time <- "Adult"
ASD <- read_tsv("../../data/Revision/Adult/ASD.scdrs_group.Time_Subtype")
ASD$Disease <- "ASD"
ASD$Time <- "Adult"
BP <- read_tsv("../../data/Revision/Adult/BP.scdrs_group.Time_Subtype")
BP$Disease <- "BP"
BP$Time <- "Adult"
MDD <- read_tsv("../../data/Revision/Adult/MDD.scdrs_group.Time_Subtype")
MDD$Disease <- "MDD"
MDD$Time <- "Adult"
OCD <- read_tsv("../../data/Revision/Adult/OCD.scdrs_group.Time_Subtype")
OCD$Disease <- "OCD"
OCD$Time <- "Adult"
SCZ <- read_tsv("../../data/Revision/Adult/SCZ.scdrs_group.Time_Subtype")
SCZ$Disease <- "SCZ"
SCZ$Time <- "Adult"
TS <- read_tsv("../../data/Revision/Adult/TS.scdrs_group.Time_Subtype")
TS$Disease <- "TS"
TS$Time <- "Adult"
Adult_Disease <- rbind(ADHD,ANO,ASD,BP,MDD,OCD,SCZ,TS)

All_Disease_separate <- rbind(P1_Disease,P4_Disease,P10_Disease,Adult_Disease)
write.csv(All_Disease_separate, "../../data/Revision/All_Disease_separate.csv",
          row.names = F)
```

```{r fig.width=10, fig.height=6}
All_Disease_separate <- read.csv("../../data/Revision/All_Disease_separate.csv")
disease_result <- All_Disease_separate

order <- paste(rep(c("P1","P4","P10","Adult"), each=21),
               rep(names(col_SubType),4))
order <- order[order %in% disease_result$group]
disease_result$group <- factor(disease_result$group, levels = order)
disease_result$Time <- factor(disease_result$Time, levels = c("P1","P4","P10","Adult"))

Figure_6A <- 
  ggplot(data = disease_result, mapping = aes(x = group, y = assoc_mcz, fill = Time)) +
  geom_bar(stat = 'identity') + 
  facet_grid(Disease ~ .) + 
  scale_fill_manual(values = col_Time) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7),
        panel.grid = element_blank(), panel.border = element_blank(),
        legend.position = "top")
Figure_6A
```


```{r}
# P1
ADHD <- read_tsv("../../data/Revision/All/ADHD.scdrs_group.Time_Subtype")
ADHD$Disease <- "ADHD"
ANO <- read_tsv("../../data/Revision/All/ANO.scdrs_group.Time_Subtype")
ANO$Disease <- "ANO"
ASD <- read_tsv("../../data/Revision/All/ASD.scdrs_group.Time_Subtype")
ASD$Disease <- "ASD"
BP <- read_tsv("../../data/Revision/All/BP.scdrs_group.Time_Subtype")
BP$Disease <- "BP"
MDD <- read_tsv("../../data/Revision/All/MDD.scdrs_group.Time_Subtype")
MDD$Disease <- "MDD"
OCD <- read_tsv("../../data/Revision/All/OCD.scdrs_group.Time_Subtype")
OCD$Disease <- "OCD"
SCZ <- read_tsv("../../data/Revision/All/SCZ.scdrs_group.Time_Subtype")
SCZ$Disease <- "SCZ"
TS <- read_tsv("../../data/Revision/All/TS.scdrs_group.Time_Subtype")
TS$Disease <- "TS"
All_Disease <- rbind(ADHD,ANO,ASD,BP,MDD,OCD,SCZ,TS)
All_Disease$Time <- as.character(lapply(All_Disease$group, function(x){strsplit(x, " ")[[1]][1]}))
write.csv(All_Disease, "../../data/Revision/All_Disease.csv",
          row.names = F)
```


```{r fig.width=10, fig.height=6}
All_Disease <- read.csv("../../data/Revision/All_Disease.csv")
disease_result <- All_Disease

order <- paste(rep(c("P1","P4","P10","Adult"), each=21),
               rep(names(col_SubType),4))
order <- order[order %in% disease_result$group]
disease_result$group <- factor(disease_result$group, levels = order)
disease_result$Time <- factor(disease_result$Time, levels = c("P1","P4","P10","Adult"))

Figure_6A <- 
  ggplot(data = disease_result, mapping = aes(x = group, y = assoc_mcz, fill = Time)) +
  geom_bar(stat = 'identity') + 
  facet_grid(Disease ~ .) + 
  scale_fill_manual(values = col_Time) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 7),
        panel.grid = element_blank(), panel.border = element_blank(),
        legend.position = "top")
Figure_6A
```

```{r}
GWAS_gene <- read_tsv("../../data/Revision/processed_geneset.gs")

#ADHD
str_pairs <- unlist(strsplit(GWAS_gene$GENESET[1], ","))
ADHD <- data.frame(
  ADHD_Gene = sapply(strsplit(str_pairs, ":"), function(x) x[1]),
  ADHD_Weight = as.numeric(sapply(strsplit(str_pairs, ":"), function(x) x[2]))
)
ADHD$ADHD_Gene <- str_to_title(ADHD$ADHD_Gene)

#ANO
str_pairs <- unlist(strsplit(GWAS_gene$GENESET[5], ","))
ANO <- data.frame(
  ANO_Gene = sapply(strsplit(str_pairs, ":"), function(x) x[1]),
  ANO_Weight = as.numeric(sapply(strsplit(str_pairs, ":"), function(x) x[2]))
)
ANO$ANO_Gene <- str_to_title(ANO$ANO_Gene)

#ASD
str_pairs <- unlist(strsplit(GWAS_gene$GENESET[6], ","))
ASD <- data.frame(
  ASD_Gene = sapply(strsplit(str_pairs, ":"), function(x) x[1]),
  ASD_Weight = as.numeric(sapply(strsplit(str_pairs, ":"), function(x) x[2]))
)
ASD$ASD_Gene <- str_to_title(ASD$ASD_Gene)

#BP
str_pairs <- unlist(strsplit(GWAS_gene$GENESET[2], ","))
BP <- data.frame(
  BP_Gene = sapply(strsplit(str_pairs, ":"), function(x) x[1]),
  BP_Weight = as.numeric(sapply(strsplit(str_pairs, ":"), function(x) x[2]))
)
BP$BP_Gene <- str_to_title(BP$BP_Gene)

#MDD
str_pairs <- unlist(strsplit(GWAS_gene$GENESET[3], ","))
MDD <- data.frame(
  MDD_Gene = sapply(strsplit(str_pairs, ":"), function(x) x[1]),
  MDD_Weight = as.numeric(sapply(strsplit(str_pairs, ":"), function(x) x[2]))
)
MDD$MDD_Gene <- str_to_title(MDD$MDD_Gene)

#OCD
str_pairs <- unlist(strsplit(GWAS_gene$GENESET[7], ","))
OCD <- data.frame(
  OCD_Gene = sapply(strsplit(str_pairs, ":"), function(x) x[1]),
  OCD_Weight = as.numeric(sapply(strsplit(str_pairs, ":"), function(x) x[2]))
)
OCD$OCD_Gene <- str_to_title(OCD$OCD_Gene)

#SCZ
str_pairs <- unlist(strsplit(GWAS_gene$GENESET[4], ","))
SCZ <- data.frame(
  SCZ_Gene = sapply(strsplit(str_pairs, ":"), function(x) x[1]),
  SCZ_Weight = as.numeric(sapply(strsplit(str_pairs, ":"), function(x) x[2]))
)
SCZ$SCZ_Gene <- str_to_title(SCZ$SCZ_Gene)

#TS
str_pairs <- unlist(strsplit(GWAS_gene$GENESET[8], ","))
TS <- data.frame(
  TS_Gene = sapply(strsplit(str_pairs, ":"), function(x) x[1]),
  TS_Weight = as.numeric(sapply(strsplit(str_pairs, ":"), function(x) x[2]))
)
TS$TS_Gene <- str_to_title(TS$TS_Gene)

Gene_weight <- cbind(ADHD,ANO,ASD,BP,MDD,OCD,SCZ,TS)
write.csv(Gene_weight, "../../data/Revision/Gene_weight.csv", row.names = F)
```


## cellpose

```{r}
P10 <- read.csv("../../Figure/基因表达比较/基因表达比较/cellpose_csv/P10.csv")
Adult <- read.csv("../../Figure/基因表达比较/基因表达比较/cellpose_csv/Adult.csv")
P10$Coexp <- log1p((P10$Sema3d+P10$Plxna1)/2)
Adult$Coexp <- log1p((Adult$Sema3d+Adult$Plxna1)/2)

```

```{r fig.width=10, fig.height=4}
p1 <- ggplot(P10, aes(x=x, y=y, color=Coexp)) +
  geom_point(size=3) +
  theme_bw() +
  scale_colour_gradientn(colours = rev(sciRcolor::pal_scircolor(83)))

p2 <- ggplot(Adult, aes(x=x, y=y, color=Coexp)) +
  geom_point(size=3) +
  theme_bw() +
  scale_colour_gradientn(colours = rev(sciRcolor::pal_scircolor(83)))

plot_grid(p1, p2, ncol = 2)
```


```{r}
library(ggsignif)

df <- data.frame(
  x=c(rep("P10",nrow(P10)), rep("Adult",nrow(Adult))),
  y=c(P10$Coexp, Adult$Coexp)
)
df$x <- factor(df$x, levels = c("P10","Adult"))

ggplot(df, aes(x=x, y=y, fill=x)) +
  geom_boxplot() +
  theme_classic() +
  scale_fill_manual(values = col_Time) +
  geom_signif(comparisons=list(c("P10","Adult")),
              color = "black",
              test="t.test", test.args=list(var.equal=T, alternative="two.side"),
              y_position=c(3),
              size = 1.5, textsize = 6, parse=T)
```



```{r}
load("../../data/spagene/LRpair_human.rds")
load("../../data/spagene/mob_raw.rds")
```

```{r}
LR_score <- function(data, k){
  expr <- t(data[,c("Sema3d", "Plxna1")])
  location <- data[,c("x", "y")]
  LRpair <- c("Sema3d","Plxna1")
  nnmatrix <- RANN::nn2(location, k=k)$nn.idx
  ligand <- expr[LRpair[1],]
  receptor <- expr[LRpair[2],]
  LRexp <- rbind(ligand,receptor)
  neighexp <- apply(nnmatrix,1,function(x){apply(LRexp[,x[2:k]],1,max)})
  LRadd <- pmax(LRexp[1,]*neighexp[2,], LRexp[2,]*neighexp[1,])
  LRadd_max <- quantile(LRadd, probs=0.95)
  LRadd[LRadd>LRadd_max] <- LRadd_max
  tmpLRadd <- data.frame(x=location[,1], y=location[,2], LR=LRadd)
  tmpLRadd$LR <- log1p(tmpLRadd$LR)
  return(tmpLRadd$LR)
}

P10 <- read.csv("../../Figure/基因表达比较/基因表达比较/cellpose_csv/P10.csv")
Adult <- read.csv("../../Figure/基因表达比较/基因表达比较/cellpose_csv/Adult.csv")
P10$Sema3d_Plxna1 <- LR_score(P10, 5)
Adult$Sema3d_Plxna1 <- LR_score(Adult, 5)


ggplot(P10_expr, aes(x=x,y=y,col=Sema3d_Plxna1)) +
  geom_point(size=2) +
  scale_colour_gradientn(colours = rev(sciRcolor::pal_scircolor(83)),
                         limit=c(0,6)) +
  xlab("") +
  ylab("") +
  theme(axis.line=element_blank(),axis.text.x=element_blank(),
        axis.text.y=element_blank(),axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank())+labs(color = "LR")
```

```{r}
library(imager)
library(spatstat.geom)

P10_mask <- load.image("../../Figure/基因表达比较/基因表达比较/cellpose_csv/P10_mask.png")
Adult_mask <- load.image("../../Figure/基因表达比较/基因表达比较/cellpose_csv/Adult_mask.png")

mask <- P10_mask
expr <- P10
  
mask_df <- as.data.frame(mask, wide = "c") %>% 
  rename(cell_id = c.1)
mask_df <- mask_df[mask_df$cell_id !=0,]
cell_id <- unique(mask_df$cell_id)
mask_df$exp <- expr$Sema3d_Plxna1[match(mask_df$cell_id, cell_id)]
mask_df$y <- -mask_df$y
```

```{r fig.width=6, fig.height=6}
p <- ggplot(mask_df, aes(x=x,y=y,color=exp)) +
  geom_point(size=0.5) +
  scale_colour_gradientn(colours = rev(sciRcolor::pal_scircolor(85)),
                         limit=c(0,6)) +
  labs(x="", y="") +
  theme_void() +
  theme(panel.grid = element_blank(),
        legend.position = "none") +
  coord_fixed()
  
p
```

```{r}
#| eval: false

ggsave("../../Figure/Figure5/Figure_5J_P10.png", plot = p, 
       height = 6, width = 6, units = "in")
```


```{r fig.width=5, fig.height=5}
library(ggsignif)

df <- data.frame(
  x=c(rep("P10",nrow(P10)), rep("Adult",nrow(Adult))),
  y=c(P10$Sema3d_Plxna1, Adult$Sema3d_Plxna1)
)
df$x <- factor(df$x, levels = c("P10","Adult"))

p <- ggplot(df, aes(x=x, y=y, fill=x)) +
  geom_boxplot() +
  theme_classic(base_size = 15) +
  theme(legend.position = "none") +
  scale_fill_manual(values = col_Time) +
  scale_y_continuous(limits = c(0,6)) +
  labs(x="", y="Sema3d_Plxna1 expression")
p
```

```{r}
#| eval: false

ggsave("../../Figure/Figure5/Figure_5K.pdf", plot = p, 
       height = 5, width = 5, units = "in")
```

```{r}
p <- t.test(P10$Sema3d_Plxna1, Adult$Sema3d_Plxna1, alternative = "two.sided",
       paired = FALSE)
p$p.value
```


