```{r}
library(ggplot2)
```


## 图4-8

```{r}
P1_metadata <- read.csv("../../data/rds/ST_data/stereo-seq/P1_metadata.csv",
                        row.names = 1)
Brain_scc <- c(0,2,3,4,5,7,8,9,10,13,19,27,30,31,33,35)
P1_metadata <- P1_metadata[P1_metadata$scc_smooth %in% Brain_scc,]
P1_PFC <- read.csv("../data/Figure1/P1_cell2location.csv", row.names = 1)
P1_metadata$PFC <- "Other"
P1_metadata[rownames(P1_PFC),"PFC"] <- "PFC"
df <- P1_metadata
theta <- pi*0.8/3
df$x_rotated <- df$Y * cos(theta) - df$X * sin(theta)
df$y_rotated <- -(df$Y * sin(theta) + df$X * cos(theta))
```

```{r fig.width=8, fig.height=4}
P1 <- 
  ggplot(df, aes(x=x_rotated, y=y_rotated, color=as.character(PFC))) +
  geom_point(size=0.2) +
  scale_color_manual(values = c("PFC"="#342a85", "Other"="lightgray")) +
  coord_fixed() +
  theme_void() +
  theme(legend.position = "none")
P1
```

```{r}
ggsave("../../Figure/毕业论文/图4-8-P1_stereo_PFC.pdf", plot = P1,
       height = 4, width = 8, units = "in")
```

```{r}
P77_metadata <- read.csv("../../data/rds/ST_data/stereo-seq/P77_metadata.csv",
                        row.names = 1)
Brain_scc <- c(4,7,10,13,14,16,17)
P77_metadata <- P77_metadata[P77_metadata$scc_smooth %in% Brain_scc,]
P77_PFC <- read.csv("../data/Figure1/P77_cell2location.csv", row.names = 1)
P77_metadata$PFC <- "Other"
P77_metadata[rownames(P77_PFC),"PFC"] <- "PFC"
df <- P77_metadata
theta <- pi
df$x_rotated <- df$Y * cos(theta) - df$X * sin(theta)
df$y_rotated <- -(df$Y * sin(theta) + df$X * cos(theta))
```

```{r fig.width=8, fig.height=4}
P77 <- 
  ggplot(df, aes(x=x_rotated, y=y_rotated, color=as.character(PFC))) +
  geom_point(size=0.1) +
  scale_color_manual(values = c("PFC"="#342a85", "Other"="lightgray")) +
  coord_fixed() +
  theme_void() +
  theme(legend.position = "none")
P77
```

```{r}
ggsave("../../Figure/毕业论文/图4-8-P77_stereo_PFC.pdf", plot = P77,
       height = 4, width = 8, units = "in")
```



